# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: causal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import anna_pb2 as anna__pb2
from . import cloudburst_pb2 as cloudburst__pb2
from . import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='causal.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63\x61usal.proto\x1a\nanna.proto\x1a\x10\x63loudburst.proto\x1a\x0cshared.proto\"F\n\x0b\x43\x61usalTuple\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x19\n\x05\x65rror\x18\x03 \x01(\x0e\x32\n.AnnaError\"\xa8\x02\n\rCausalRequest\x12%\n\x0b\x63onsistency\x18\x01 \x01(\x0e\x32\x10.ConsistencyType\x12\n\n\x02id\x18\x02 \x01(\t\x12\x1c\n\x06tuples\x18\x03 \x03(\x0b\x32\x0c.CausalTuple\x12\x17\n\x0f\x66uture_read_set\x18\x04 \x03(\t\x12\x46\n\x15key_version_locations\x18\x05 \x03(\x0b\x32\'.CausalRequest.KeyVersionLocationsEntry\x12\x18\n\x10response_address\x18\x06 \x01(\t\x1aK\n\x18KeyVersionLocationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.KeyVersionList:\x02\x38\x01\"t\n\x0e\x43\x61usalResponse\x12\x1c\n\x06tuples\x18\x01 \x03(\x0b\x32\x0c.CausalTuple\x12!\n\x19key_version_query_address\x18\x02 \x01(\t\x12!\n\x0ckey_versions\x18\x03 \x03(\x0b\x32\x0b.KeyVersion\"G\n\x11KeyVersionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x10response_address\x18\x02 \x01(\t\x12\x0c\n\x04keys\x18\x03 \x03(\t\">\n\x12KeyVersionResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1c\n\x06tuples\x18\x02 \x03(\x0b\x32\x0c.CausalTupleb\x06proto3')
  ,
  dependencies=[anna__pb2.DESCRIPTOR,cloudburst__pb2.DESCRIPTOR,shared__pb2.DESCRIPTOR,])




_CAUSALTUPLE = _descriptor.Descriptor(
  name='CausalTuple',
  full_name='CausalTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CausalTuple.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='CausalTuple.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='CausalTuple.error', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=130,
)


_CAUSALREQUEST_KEYVERSIONLOCATIONSENTRY = _descriptor.Descriptor(
  name='KeyVersionLocationsEntry',
  full_name='CausalRequest.KeyVersionLocationsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CausalRequest.KeyVersionLocationsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='CausalRequest.KeyVersionLocationsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=429,
)

_CAUSALREQUEST = _descriptor.Descriptor(
  name='CausalRequest',
  full_name='CausalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consistency', full_name='CausalRequest.consistency', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='CausalRequest.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tuples', full_name='CausalRequest.tuples', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='future_read_set', full_name='CausalRequest.future_read_set', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_version_locations', full_name='CausalRequest.key_version_locations', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_address', full_name='CausalRequest.response_address', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CAUSALREQUEST_KEYVERSIONLOCATIONSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=429,
)


_CAUSALRESPONSE = _descriptor.Descriptor(
  name='CausalResponse',
  full_name='CausalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tuples', full_name='CausalResponse.tuples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_version_query_address', full_name='CausalResponse.key_version_query_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_versions', full_name='CausalResponse.key_versions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=547,
)


_KEYVERSIONREQUEST = _descriptor.Descriptor(
  name='KeyVersionRequest',
  full_name='KeyVersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='KeyVersionRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_address', full_name='KeyVersionRequest.response_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keys', full_name='KeyVersionRequest.keys', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=620,
)


_KEYVERSIONRESPONSE = _descriptor.Descriptor(
  name='KeyVersionResponse',
  full_name='KeyVersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='KeyVersionResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tuples', full_name='KeyVersionResponse.tuples', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=622,
  serialized_end=684,
)

_CAUSALTUPLE.fields_by_name['error'].enum_type = anna__pb2._ANNAERROR
_CAUSALREQUEST_KEYVERSIONLOCATIONSENTRY.fields_by_name['value'].message_type = shared__pb2._KEYVERSIONLIST
_CAUSALREQUEST_KEYVERSIONLOCATIONSENTRY.containing_type = _CAUSALREQUEST
_CAUSALREQUEST.fields_by_name['consistency'].enum_type = cloudburst__pb2._CONSISTENCYTYPE
_CAUSALREQUEST.fields_by_name['tuples'].message_type = _CAUSALTUPLE
_CAUSALREQUEST.fields_by_name['key_version_locations'].message_type = _CAUSALREQUEST_KEYVERSIONLOCATIONSENTRY
_CAUSALRESPONSE.fields_by_name['tuples'].message_type = _CAUSALTUPLE
_CAUSALRESPONSE.fields_by_name['key_versions'].message_type = shared__pb2._KEYVERSION
_KEYVERSIONRESPONSE.fields_by_name['tuples'].message_type = _CAUSALTUPLE
DESCRIPTOR.message_types_by_name['CausalTuple'] = _CAUSALTUPLE
DESCRIPTOR.message_types_by_name['CausalRequest'] = _CAUSALREQUEST
DESCRIPTOR.message_types_by_name['CausalResponse'] = _CAUSALRESPONSE
DESCRIPTOR.message_types_by_name['KeyVersionRequest'] = _KEYVERSIONREQUEST
DESCRIPTOR.message_types_by_name['KeyVersionResponse'] = _KEYVERSIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CausalTuple = _reflection.GeneratedProtocolMessageType('CausalTuple', (_message.Message,), dict(
  DESCRIPTOR = _CAUSALTUPLE,
  __module__ = 'causal_pb2'
  # @@protoc_insertion_point(class_scope:CausalTuple)
  ))
_sym_db.RegisterMessage(CausalTuple)

CausalRequest = _reflection.GeneratedProtocolMessageType('CausalRequest', (_message.Message,), dict(

  KeyVersionLocationsEntry = _reflection.GeneratedProtocolMessageType('KeyVersionLocationsEntry', (_message.Message,), dict(
    DESCRIPTOR = _CAUSALREQUEST_KEYVERSIONLOCATIONSENTRY,
    __module__ = 'causal_pb2'
    # @@protoc_insertion_point(class_scope:CausalRequest.KeyVersionLocationsEntry)
    ))
  ,
  DESCRIPTOR = _CAUSALREQUEST,
  __module__ = 'causal_pb2'
  # @@protoc_insertion_point(class_scope:CausalRequest)
  ))
_sym_db.RegisterMessage(CausalRequest)
_sym_db.RegisterMessage(CausalRequest.KeyVersionLocationsEntry)

CausalResponse = _reflection.GeneratedProtocolMessageType('CausalResponse', (_message.Message,), dict(
  DESCRIPTOR = _CAUSALRESPONSE,
  __module__ = 'causal_pb2'
  # @@protoc_insertion_point(class_scope:CausalResponse)
  ))
_sym_db.RegisterMessage(CausalResponse)

KeyVersionRequest = _reflection.GeneratedProtocolMessageType('KeyVersionRequest', (_message.Message,), dict(
  DESCRIPTOR = _KEYVERSIONREQUEST,
  __module__ = 'causal_pb2'
  # @@protoc_insertion_point(class_scope:KeyVersionRequest)
  ))
_sym_db.RegisterMessage(KeyVersionRequest)

KeyVersionResponse = _reflection.GeneratedProtocolMessageType('KeyVersionResponse', (_message.Message,), dict(
  DESCRIPTOR = _KEYVERSIONRESPONSE,
  __module__ = 'causal_pb2'
  # @@protoc_insertion_point(class_scope:KeyVersionResponse)
  ))
_sym_db.RegisterMessage(KeyVersionResponse)


_CAUSALREQUEST_KEYVERSIONLOCATIONSENTRY._options = None
# @@protoc_insertion_point(module_scope)
