# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metadata.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0emetadata.proto\"m\n\x16ServerThreadStatistics\x12\x1b\n\x13storage_consumption\x18\x01 \x01(\x04\x12\x11\n\toccupancy\x18\x02 \x01(\x01\x12\r\n\x05\x65poch\x18\x03 \x01(\r\x12\x14\n\x0c\x61\x63\x63\x65ss_count\x18\x04 \x01(\r\"e\n\rKeyAccessData\x12%\n\x04keys\x18\x01 \x03(\x0b\x32\x17.KeyAccessData.KeyCount\x1a-\n\x08KeyCount\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_count\x18\x02 \x01(\r\"\xdc\x01\n\x11\x43lusterMembership\x12\x30\n\x05tiers\x18\x01 \x03(\x0b\x32!.ClusterMembership.TierMembership\x1a\x94\x01\n\x0eTierMembership\x12\x16\n\x07tier_id\x18\x01 \x01(\x0e\x32\x05.Tier\x12\x39\n\x07servers\x18\x02 \x03(\x0b\x32(.ClusterMembership.TierMembership.Server\x1a/\n\x06Server\x12\x11\n\tpublic_ip\x18\x01 \x01(\t\x12\x12\n\nprivate_ip\x18\x02 \x01(\t\"\\\n\x0bKeySizeData\x12\'\n\tkey_sizes\x18\x01 \x03(\x0b\x32\x14.KeySizeData.KeySize\x1a$\n\x07KeySize\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\r\"\xc1\x01\n\x11ReplicationFactor\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x33\n\x06global\x18\x02 \x03(\x0b\x32#.ReplicationFactor.ReplicationValue\x12\x32\n\x05local\x18\x03 \x03(\x0b\x32#.ReplicationFactor.ReplicationValue\x1a\x36\n\x10ReplicationValue\x12\x13\n\x04tier\x18\x01 \x01(\x0e\x32\x05.Tier\x12\r\n\x05value\x18\x02 \x01(\r\">\n\x17ReplicationFactorUpdate\x12#\n\x07updates\x18\x01 \x03(\x0b\x32\x12.ReplicationFactor*?\n\x04Tier\x12\x14\n\x10TIER_UNSPECIFIED\x10\x00\x12\n\n\x06MEMORY\x10\x01\x12\x08\n\x04\x44ISK\x10\x02\x12\x0b\n\x07ROUTING\x10\x03\x62\x06proto3')
)

_TIER = _descriptor.EnumDescriptor(
  name='Tier',
  full_name='Tier',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TIER_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEMORY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISK', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROUTING', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=809,
  serialized_end=872,
)
_sym_db.RegisterEnumDescriptor(_TIER)

Tier = enum_type_wrapper.EnumTypeWrapper(_TIER)
TIER_UNSPECIFIED = 0
MEMORY = 1
DISK = 2
ROUTING = 3



_SERVERTHREADSTATISTICS = _descriptor.Descriptor(
  name='ServerThreadStatistics',
  full_name='ServerThreadStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='storage_consumption', full_name='ServerThreadStatistics.storage_consumption', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='occupancy', full_name='ServerThreadStatistics.occupancy', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch', full_name='ServerThreadStatistics.epoch', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='access_count', full_name='ServerThreadStatistics.access_count', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=127,
)


_KEYACCESSDATA_KEYCOUNT = _descriptor.Descriptor(
  name='KeyCount',
  full_name='KeyAccessData.KeyCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KeyAccessData.KeyCount.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='access_count', full_name='KeyAccessData.KeyCount.access_count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=230,
)

_KEYACCESSDATA = _descriptor.Descriptor(
  name='KeyAccessData',
  full_name='KeyAccessData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='KeyAccessData.keys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_KEYACCESSDATA_KEYCOUNT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=230,
)


_CLUSTERMEMBERSHIP_TIERMEMBERSHIP_SERVER = _descriptor.Descriptor(
  name='Server',
  full_name='ClusterMembership.TierMembership.Server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_ip', full_name='ClusterMembership.TierMembership.Server.public_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='private_ip', full_name='ClusterMembership.TierMembership.Server.private_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=453,
)

_CLUSTERMEMBERSHIP_TIERMEMBERSHIP = _descriptor.Descriptor(
  name='TierMembership',
  full_name='ClusterMembership.TierMembership',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tier_id', full_name='ClusterMembership.TierMembership.tier_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='servers', full_name='ClusterMembership.TierMembership.servers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CLUSTERMEMBERSHIP_TIERMEMBERSHIP_SERVER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=453,
)

_CLUSTERMEMBERSHIP = _descriptor.Descriptor(
  name='ClusterMembership',
  full_name='ClusterMembership',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tiers', full_name='ClusterMembership.tiers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CLUSTERMEMBERSHIP_TIERMEMBERSHIP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=453,
)


_KEYSIZEDATA_KEYSIZE = _descriptor.Descriptor(
  name='KeySize',
  full_name='KeySizeData.KeySize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KeySizeData.KeySize.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='KeySizeData.KeySize.size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=547,
)

_KEYSIZEDATA = _descriptor.Descriptor(
  name='KeySizeData',
  full_name='KeySizeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_sizes', full_name='KeySizeData.key_sizes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_KEYSIZEDATA_KEYSIZE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=547,
)


_REPLICATIONFACTOR_REPLICATIONVALUE = _descriptor.Descriptor(
  name='ReplicationValue',
  full_name='ReplicationFactor.ReplicationValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tier', full_name='ReplicationFactor.ReplicationValue.tier', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ReplicationFactor.ReplicationValue.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=689,
  serialized_end=743,
)

_REPLICATIONFACTOR = _descriptor.Descriptor(
  name='ReplicationFactor',
  full_name='ReplicationFactor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ReplicationFactor.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global', full_name='ReplicationFactor.global', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local', full_name='ReplicationFactor.local', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REPLICATIONFACTOR_REPLICATIONVALUE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=743,
)


_REPLICATIONFACTORUPDATE = _descriptor.Descriptor(
  name='ReplicationFactorUpdate',
  full_name='ReplicationFactorUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='updates', full_name='ReplicationFactorUpdate.updates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=745,
  serialized_end=807,
)

_KEYACCESSDATA_KEYCOUNT.containing_type = _KEYACCESSDATA
_KEYACCESSDATA.fields_by_name['keys'].message_type = _KEYACCESSDATA_KEYCOUNT
_CLUSTERMEMBERSHIP_TIERMEMBERSHIP_SERVER.containing_type = _CLUSTERMEMBERSHIP_TIERMEMBERSHIP
_CLUSTERMEMBERSHIP_TIERMEMBERSHIP.fields_by_name['tier_id'].enum_type = _TIER
_CLUSTERMEMBERSHIP_TIERMEMBERSHIP.fields_by_name['servers'].message_type = _CLUSTERMEMBERSHIP_TIERMEMBERSHIP_SERVER
_CLUSTERMEMBERSHIP_TIERMEMBERSHIP.containing_type = _CLUSTERMEMBERSHIP
_CLUSTERMEMBERSHIP.fields_by_name['tiers'].message_type = _CLUSTERMEMBERSHIP_TIERMEMBERSHIP
_KEYSIZEDATA_KEYSIZE.containing_type = _KEYSIZEDATA
_KEYSIZEDATA.fields_by_name['key_sizes'].message_type = _KEYSIZEDATA_KEYSIZE
_REPLICATIONFACTOR_REPLICATIONVALUE.fields_by_name['tier'].enum_type = _TIER
_REPLICATIONFACTOR_REPLICATIONVALUE.containing_type = _REPLICATIONFACTOR
_REPLICATIONFACTOR.fields_by_name['global'].message_type = _REPLICATIONFACTOR_REPLICATIONVALUE
_REPLICATIONFACTOR.fields_by_name['local'].message_type = _REPLICATIONFACTOR_REPLICATIONVALUE
_REPLICATIONFACTORUPDATE.fields_by_name['updates'].message_type = _REPLICATIONFACTOR
DESCRIPTOR.message_types_by_name['ServerThreadStatistics'] = _SERVERTHREADSTATISTICS
DESCRIPTOR.message_types_by_name['KeyAccessData'] = _KEYACCESSDATA
DESCRIPTOR.message_types_by_name['ClusterMembership'] = _CLUSTERMEMBERSHIP
DESCRIPTOR.message_types_by_name['KeySizeData'] = _KEYSIZEDATA
DESCRIPTOR.message_types_by_name['ReplicationFactor'] = _REPLICATIONFACTOR
DESCRIPTOR.message_types_by_name['ReplicationFactorUpdate'] = _REPLICATIONFACTORUPDATE
DESCRIPTOR.enum_types_by_name['Tier'] = _TIER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerThreadStatistics = _reflection.GeneratedProtocolMessageType('ServerThreadStatistics', (_message.Message,), dict(
  DESCRIPTOR = _SERVERTHREADSTATISTICS,
  __module__ = 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:ServerThreadStatistics)
  ))
_sym_db.RegisterMessage(ServerThreadStatistics)

KeyAccessData = _reflection.GeneratedProtocolMessageType('KeyAccessData', (_message.Message,), dict(

  KeyCount = _reflection.GeneratedProtocolMessageType('KeyCount', (_message.Message,), dict(
    DESCRIPTOR = _KEYACCESSDATA_KEYCOUNT,
    __module__ = 'metadata_pb2'
    # @@protoc_insertion_point(class_scope:KeyAccessData.KeyCount)
    ))
  ,
  DESCRIPTOR = _KEYACCESSDATA,
  __module__ = 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:KeyAccessData)
  ))
_sym_db.RegisterMessage(KeyAccessData)
_sym_db.RegisterMessage(KeyAccessData.KeyCount)

ClusterMembership = _reflection.GeneratedProtocolMessageType('ClusterMembership', (_message.Message,), dict(

  TierMembership = _reflection.GeneratedProtocolMessageType('TierMembership', (_message.Message,), dict(

    Server = _reflection.GeneratedProtocolMessageType('Server', (_message.Message,), dict(
      DESCRIPTOR = _CLUSTERMEMBERSHIP_TIERMEMBERSHIP_SERVER,
      __module__ = 'metadata_pb2'
      # @@protoc_insertion_point(class_scope:ClusterMembership.TierMembership.Server)
      ))
    ,
    DESCRIPTOR = _CLUSTERMEMBERSHIP_TIERMEMBERSHIP,
    __module__ = 'metadata_pb2'
    # @@protoc_insertion_point(class_scope:ClusterMembership.TierMembership)
    ))
  ,
  DESCRIPTOR = _CLUSTERMEMBERSHIP,
  __module__ = 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:ClusterMembership)
  ))
_sym_db.RegisterMessage(ClusterMembership)
_sym_db.RegisterMessage(ClusterMembership.TierMembership)
_sym_db.RegisterMessage(ClusterMembership.TierMembership.Server)

KeySizeData = _reflection.GeneratedProtocolMessageType('KeySizeData', (_message.Message,), dict(

  KeySize = _reflection.GeneratedProtocolMessageType('KeySize', (_message.Message,), dict(
    DESCRIPTOR = _KEYSIZEDATA_KEYSIZE,
    __module__ = 'metadata_pb2'
    # @@protoc_insertion_point(class_scope:KeySizeData.KeySize)
    ))
  ,
  DESCRIPTOR = _KEYSIZEDATA,
  __module__ = 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:KeySizeData)
  ))
_sym_db.RegisterMessage(KeySizeData)
_sym_db.RegisterMessage(KeySizeData.KeySize)

ReplicationFactor = _reflection.GeneratedProtocolMessageType('ReplicationFactor', (_message.Message,), dict(

  ReplicationValue = _reflection.GeneratedProtocolMessageType('ReplicationValue', (_message.Message,), dict(
    DESCRIPTOR = _REPLICATIONFACTOR_REPLICATIONVALUE,
    __module__ = 'metadata_pb2'
    # @@protoc_insertion_point(class_scope:ReplicationFactor.ReplicationValue)
    ))
  ,
  DESCRIPTOR = _REPLICATIONFACTOR,
  __module__ = 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:ReplicationFactor)
  ))
_sym_db.RegisterMessage(ReplicationFactor)
_sym_db.RegisterMessage(ReplicationFactor.ReplicationValue)

ReplicationFactorUpdate = _reflection.GeneratedProtocolMessageType('ReplicationFactorUpdate', (_message.Message,), dict(
  DESCRIPTOR = _REPLICATIONFACTORUPDATE,
  __module__ = 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:ReplicationFactorUpdate)
  ))
_sym_db.RegisterMessage(ReplicationFactorUpdate)


# @@protoc_insertion_point(module_scope)
