# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tasc.proto',
  package='tasc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntasc.proto\x12\x04tasc\x1a\x1bgoogle/protobuf/empty.proto\"J\n\x0eTransactionTag\x12\x0b\n\x03tid\x18\x01 \x01(\t\x12+\n\x06status\x18\x02 \x01(\x0e\x32\x1b.tasc.TascTransactionStatus\"k\n\x0bTascRequest\x12\x0b\n\x03tid\x18\x01 \x01(\t\x12(\n\x05pairs\x18\x02 \x03(\x0b\x32\x19.tasc.TascRequest.KeyPair\x1a%\n\x07KeyPair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"#\n\x13TransactionWriteSet\x12\x0c\n\x04keys\x18\x01 \x03(\t*@\n\x15TascTransactionStatus\x12\x0b\n\x07RUNNING\x10\x00\x12\r\n\tCOMMITTED\x10\x01\x12\x0b\n\x07\x41\x42ORTED\x10\x02\x32\xb0\x02\n\x04Tasc\x12\x42\n\x10StartTransaction\x12\x16.google.protobuf.Empty\x1a\x14.tasc.TransactionTag\"\x00\x12.\n\x04Read\x12\x11.tasc.TascRequest\x1a\x11.tasc.TascRequest\"\x00\x12/\n\x05Write\x12\x11.tasc.TascRequest\x1a\x11.tasc.TascRequest\"\x00\x12\x41\n\x11\x43ommitTransaction\x12\x14.tasc.TransactionTag\x1a\x14.tasc.TransactionTag\"\x00\x12@\n\x10\x41\x62ortTransaction\x12\x14.tasc.TransactionTag\x1a\x14.tasc.TransactionTag\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])

_TASCTRANSACTIONSTATUS = _descriptor.EnumDescriptor(
  name='TascTransactionStatus',
  full_name='tasc.TascTransactionStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMITTED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ABORTED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=271,
  serialized_end=335,
)
_sym_db.RegisterEnumDescriptor(_TASCTRANSACTIONSTATUS)

TascTransactionStatus = enum_type_wrapper.EnumTypeWrapper(_TASCTRANSACTIONSTATUS)
RUNNING = 0
COMMITTED = 1
ABORTED = 2



_TRANSACTIONTAG = _descriptor.Descriptor(
  name='TransactionTag',
  full_name='tasc.TransactionTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='tasc.TransactionTag.tid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='tasc.TransactionTag.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=123,
)


_TASCREQUEST_KEYPAIR = _descriptor.Descriptor(
  name='KeyPair',
  full_name='tasc.TascRequest.KeyPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tasc.TascRequest.KeyPair.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='tasc.TascRequest.KeyPair.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=232,
)

_TASCREQUEST = _descriptor.Descriptor(
  name='TascRequest',
  full_name='tasc.TascRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='tasc.TascRequest.tid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pairs', full_name='tasc.TascRequest.pairs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TASCREQUEST_KEYPAIR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=232,
)


_TRANSACTIONWRITESET = _descriptor.Descriptor(
  name='TransactionWriteSet',
  full_name='tasc.TransactionWriteSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='tasc.TransactionWriteSet.keys', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=269,
)

_TRANSACTIONTAG.fields_by_name['status'].enum_type = _TASCTRANSACTIONSTATUS
_TASCREQUEST_KEYPAIR.containing_type = _TASCREQUEST
_TASCREQUEST.fields_by_name['pairs'].message_type = _TASCREQUEST_KEYPAIR
DESCRIPTOR.message_types_by_name['TransactionTag'] = _TRANSACTIONTAG
DESCRIPTOR.message_types_by_name['TascRequest'] = _TASCREQUEST
DESCRIPTOR.message_types_by_name['TransactionWriteSet'] = _TRANSACTIONWRITESET
DESCRIPTOR.enum_types_by_name['TascTransactionStatus'] = _TASCTRANSACTIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionTag = _reflection.GeneratedProtocolMessageType('TransactionTag', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONTAG,
  '__module__' : 'tasc_pb2'
  # @@protoc_insertion_point(class_scope:tasc.TransactionTag)
  })
_sym_db.RegisterMessage(TransactionTag)

TascRequest = _reflection.GeneratedProtocolMessageType('TascRequest', (_message.Message,), {

  'KeyPair' : _reflection.GeneratedProtocolMessageType('KeyPair', (_message.Message,), {
    'DESCRIPTOR' : _TASCREQUEST_KEYPAIR,
    '__module__' : 'tasc_pb2'
    # @@protoc_insertion_point(class_scope:tasc.TascRequest.KeyPair)
    })
  ,
  'DESCRIPTOR' : _TASCREQUEST,
  '__module__' : 'tasc_pb2'
  # @@protoc_insertion_point(class_scope:tasc.TascRequest)
  })
_sym_db.RegisterMessage(TascRequest)
_sym_db.RegisterMessage(TascRequest.KeyPair)

TransactionWriteSet = _reflection.GeneratedProtocolMessageType('TransactionWriteSet', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONWRITESET,
  '__module__' : 'tasc_pb2'
  # @@protoc_insertion_point(class_scope:tasc.TransactionWriteSet)
  })
_sym_db.RegisterMessage(TransactionWriteSet)



_TASC = _descriptor.ServiceDescriptor(
  name='Tasc',
  full_name='tasc.Tasc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=338,
  serialized_end=642,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartTransaction',
    full_name='tasc.Tasc.StartTransaction',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TRANSACTIONTAG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='tasc.Tasc.Read',
    index=1,
    containing_service=None,
    input_type=_TASCREQUEST,
    output_type=_TASCREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='tasc.Tasc.Write',
    index=2,
    containing_service=None,
    input_type=_TASCREQUEST,
    output_type=_TASCREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CommitTransaction',
    full_name='tasc.Tasc.CommitTransaction',
    index=3,
    containing_service=None,
    input_type=_TRANSACTIONTAG,
    output_type=_TRANSACTIONTAG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AbortTransaction',
    full_name='tasc.Tasc.AbortTransaction',
    index=4,
    containing_service=None,
    input_type=_TRANSACTIONTAG,
    output_type=_TRANSACTIONTAG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASC)

DESCRIPTOR.services_by_name['Tasc'] = _TASC

# @@protoc_insertion_point(module_scope)
